apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/tedwon/starter-kotlin:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/tedwon/starter-kotlin:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: starter-kotlin
        chartPath: charts/starter-kotlin
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/tedwon/starter-kotlin"
          image.tag: "{{.DIGEST_HEX}}"
